### ISSUE TITLE
Add option to return prop values

### ISSUE THREAD

**Issue by Vadimkin** [wavebeem/jsx-info#16]
I'm using this package with jest to check that all used strings by [`react-intl`](https://www.npmjs.com/package/react-intl) are in file with localization.

So, I'm using this package to find all `<FormattedMessage id="..." defaultMessage="...">` component usage, extract it by `id` and compare that this `id` is exist in all localized files.

Unfortunately, `analyze()` method doesn't include prop values and almost methods are private, so I'm using too dirty way to use your package with `rewire` package :)

```
// All methods are private, so rewire is needed to access into them
const jsxInfoApi = rewire('jsx-info/dist/src/api');

const parseJsxInfo = jsxInfoApi.__get__('parse');
const createPropJsxInfo = jsxInfoApi.__get__('createProp');

...

const filenames = await globby([
    'containers/**/*.jsx',
    'components/**/*.jsx',
    'mappings.jsx',
  ], {
    absolute: true,
    onlyFiles: true,
    gitignore: true,
    ignore: [],
    cwd: directory,
  });

  filenames.forEach((filename) => {
    try {
      const code = fs.readFileSync(path.resolve(directory, filename), 'utf8');

      parseJsxInfo(code, {
        babelPlugins: [],
        typescript: filename.endsWith('.tsx') || filename.endsWith('.ts'),
        onlyComponents: [
          'FormattedMessage',
          'CustomHeadingComponent',
          'FormRow',
          'DataRow',
          'InfoRow',
        ],
        onComponent: ({ node }) => {
          node.openingElement.attributes.forEach((propNode) => {
            const propValue = propNode.value.value;
            const propName = createPropJsxInfo(propNode);

            // ... here propName is validated and propValue is used
          });
        },
      });
    } catch (error) {
      throw error;
    }
  });
```

It covers 99% of my cases, except variables.

What do you think is better?

1. Update `analyze()` method to include prop values as well? It might be good, but how to deal with non-string props?
2. To export private methods?
3. Keep as is :)

Thanks for this awesome package!

**Comment by wavebeem** [comment]
Hey @Vadimkin! Glad you like jsx-info.

I like option 1 here, "include prop values". I am already turning prop values into a string for searching, so it shouldn't be too hard to add this to the API.

I have some code that turns a prop value into a searchable string, like `kind="primary"` is searched for via `prop: "kind=primary"` without quotes. I would want to think a bit more about how that works, but that's the direction I would like to go.

```ts
function formatPropValue(value: Node | null): string | symbol {
  if (value === null) {
    return "true";
  }
  if (!value) {
    return EXPRESSION;
  }
  switch (value.type) {
    // TODO: Should we interpret anything else here?
    case "StringLiteral":
      return value.value;
    case "JSXExpressionContainer":
      return formatPropValue(value.expression);
    case "NumericLiteral":
    case "BooleanLiteral":
      return String(value.value);
    default:
      return EXPRESSION;
  }
}
```

This function could be expanded, though arbitrary expressions can be quite complicated, haha. Maybe I can just leave it as a symbol for now? Like `<C y={ x + 2 } />`  it could be tricky if someone expects that to be searchable as `y=x+2` since I'd have to take whitespace into account 😬 

```rb
  "lineUsage": Object {
    "div": Object {
      "x": Array [
        Object {
          "endLoc": Position {
            "column": 21,
            "line": 1,
          },
          "filename": "main.tsx",
          "prettyCode": "   1 | <div x=\"y\" />;",
          "propCode": "x",

          # --- NEW `propValue` field --- #
          "propValue": "y",
          # ----------------------------- #

          "startLoc": Position {
            "column": 5,
            "line": 1,
          },
        },
      ],
    },
  },
```

Are you interested in working on a PR for this? I definitely think it sounds like a good idea, and a lot of the work is done already. If not, I may look into this eventually. For now, your `rewire` trick is pretty cool! If it were me, I would've just copy/pasted the code from this package and changed it haha.

**Comment by Vadimkin** [comment]
Hi @wavebeem!

Thanks for your answer and long response time from me!
I came back to my home after trip, so I'll be able to implement this feature :)

I'll let you know about my progress in next few days!

**Comment by wavebeem** [comment]
Sounds good! Feel free to open a PR as soon as you want feedback.
